packages:
  - packages/*

catalog:
  "@emotion/react": "^11.13.3"
  "@mantine/core": "^7.13.0"
  "@mantine/hooks": "^7.13.0"
  "@testing-library/jest-dom": "^6.5.0"
  "@testing-library/react": "^16.0.1"
  "@testing-library/user-event": "^14.5.2"
  "@floating-ui/react": "^0.26.4"
  "@tiptap/core": "^2.7.4"
  "@tiptap/extension-text": "^2.7.4"
  "@tiptap/extension-document": "^2.7.4"
  "@tiptap/extension-history": "^2.7.4"
  "@tiptap/pm": "^2.7.4"
  "@tiptap/react": "^2.7.4"
  "@types/jest": "^29.5.13"
  "@types/katex": "^0.16.7"
  "@types/node": "^22.7.4"
  "@types/react": "^18.3.10"
  "@types/react-dom": "^18.3.0"
  "prosemirror-model": "^1.22.3"
  "prosemirror-state": "^1.4.3"
  "prosemirror-tables": "^1.5.0"
  "prosemirror-transform": "^1.10.0"
  "prosemirror-view": "^1.34.3"
  "clsx": "^2.1.1"
  "katex": "^0.16.11"
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "react-icons": "^5.3.0"
  "shiki": "^1.21.1"
  "@shikijs/monaco": "^1.21.1"
  "lodash.merge": "^4.6.2"

  "@vitejs/plugin-react-swc": "^3.7.0"
  "globals": "^15.9.0"
  "typescript": "^5.6.2"
  "typescript-eslint": "^8.7.0"
  "vite": "^5.4.8"
  "@types/lodash.foreach": "^4.5.9"
  "@types/lodash.groupby": "^4.6.9"
  "@types/lodash.merge": "^4.6.9"
